### PR TITLE
Fix wrong focus direction.

### PR DESCRIPTION
**Pull request by fulminant**
Fixed issue with incorrect focus direction when node appears conditionally.
Also, added a separate page inside the `example` project to demonstrate the problem and its solution.
Fixes https://github.com/bamlab/react-tv-space-navigation/issues/109#issue-2250291473

### CODE REVIEW

**Comment by pierpo** [comment]
Love the idea of having it in the example. It makes it so much more visible.
I'll review properly later, as I said in the issue I think it's better not to use the index as a solution 😁 

Doesn't mean we can't expose it, though!

Thanks 👍

**Comment by pierpo** [comment]
I don't think we'll need to expose the index yet. I'm not sure we want to give that ability, as it will only pollute the API and lead to unexpected behaviours 😁 
We'll see later if we really do need this, but there was a cleaner solution to your problem so I guess nothing urgent 😎

**Comment by fulminant** [comment]
Maybe you're right.
For me, setting the `index` property is a clearer way to control this behavior, but it won't work for large-scale applications.

Thanks for the update.

**Comment by pierpo** [comment]
I'm still thinking this through. If that's clearer for you, maybe we can add this feature as experimental 😁 
Would you rather have the index exposed than the solution I proposed?

In my opinion, it feels a little clunky to add index to all elements, that's what I don't like with the approach. But if people prefer the index option, I can't argue with that 😁

**Pull request closed without merging**
